import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>WattTrader</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto flex min-h-screen max-w-[92rem] flex-col gap-20 bg-white">
        <header className="flex items-center justify-between border-b border-gray-100 px-12 py-6">
          <h1 className="text-2xl font-semibold">⚡️WattTrader</h1>
          <nav className="flex items-center">
            <Link className="hover:underline" href="/sign-in">
              Get Lit
            </Link>
          </nav>
        </header>
        <section className="grid grid-cols-2 gap-8 overflow-x-hidden px-12">
          <div className="mt-16 flex flex-col gap-9">
            <h2 className="max-w-[540px] text-4xl font-semibold leading-[1.7]">
              Empowering Communities, Energizing Tomorrow: Welcome to the Future
              of Decentralized Energy Distribution.
            </h2>
            <Link
              className="w-fit rounded-md bg-green-500 px-10 py-3 text-center text-white shadow-md"
              href="/sign-in"
            >
              Get Lit ⚡️
            </Link>
          </div>
          <div className="flex justify-end">
            <div className="relative h-[540px] w-[690px] rounded-xl border-[2px] border-green-400">
              <Image
                src="/energy_dashboard.png"
                className="rounded-xl"
                fill
                alt="Energy dashboard"
              />
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
